# Generated by Django 6.0.5 on 2026-05-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_alter_event_options_rename_active_apikey_is_active_and_more'),
        ('organizations', '0002_organization_created_at_organization_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='source_type',
            field=models.CharField(choices=[('api', 'API'), ('csv', 'CSV'), ('webhook', 'Webhook')], default='api', max_length=20),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', 'timestamp'], name='ingestion_e_organiz_ed2c55_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_name'], name='ingestion_e_event_n_5686dd_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['source_type'], name='ingestion_e_source__0b68d0_idx'),
        ),
    ]
