# Generated by Django 6.0.5 on 2026-05-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_dashboardtemplate_dashboard_access_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledreport',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/pdfs/'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='png_file',
            field=models.ImageField(blank=True, null=True, upload_to='reports/pngs/'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='report_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
