# Generated by Django 6.0.5 on 2026-05-12 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboards', '0002_dashboardtemplate_dashboard_access_type_and_more'),
        ('organizations', '0002_organization_created_at_organization_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=255)),
                ('threshold_value', models.FloatField()),
                ('condition', models.CharField(choices=[('gt', 'Greater Than'), ('lt', 'Less Than')], max_length=20)),
                ('duration_minutes', models.IntegerField(default=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('triggered', 'Triggered'), ('resolved', 'Resolved'), ('muted', 'Muted')], default='active', max_length=20)),
                ('snooze_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.dashboard')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_value', models.FloatField()),
                ('message', models.TextField()),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.alertrule')),
            ],
        ),
    ]
